version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - API_KEY=${API_KEY}
      - MONGODB_URI=mongodb://mongo:27017/weatherDB
      - ALERT_THRESHOLD=${ALERT_THRESHOLD}
    depends_on:
      - mongo

volumes:
  mongo_data:
